"""Observation (obs) term library — flat functions **composing** api primitives + StateAdapter reads.

A term is ``fn(env, <knob>=<default>, ...) -> (N, d)``, called by the driver every policy step with the
contract's named knobs (``ObsTerm.params``) — the same shape as a reward term. The contract
(`contract/tasks/rl/<task>.py`) composes these into obs groups. No engine import (env is the backend).
"""
from sim.metalab.terms.obs.common import (
    action_delay,
    body_angular_velocity,
    body_contact_flags,
    body_linear_velocity,
    body_pose_in_chest,
    closest_fingertip_dist,
    closest_keypoint_max_dist,
    curriculum_hold_progress,
    curriculum_state,
    curriculum_success,
    dr_params,
    episode_step,
    fingertip_contact_steps,
    fingertip_penetration_depth,
    fingertip_relative_pos,
    fingertip_relative_pose,
    fingertip_relative_vel,
    gate_success,
    goal_dist_error,
    goal_keypoints,
    grip_count,
    hand_contact_force,
    hand_object_force_magnitude,
    instantaneous_reward,
    joint_accelerations,
    joint_gravcomp_torque_obs,
    joint_pd_torque_obs,
    joint_pose_error,
    joint_positions,
    joint_state,
    joint_torque_obs,
    joint_velocities,
    last_action,
    object_angular_velocity,
    object_goal_keypoint_success,
    object_keypoints,
    object_lifed,
    object_linear_velocity,
    object_pose,
    object_state_world,
    object_variant,
    palm_distance_error,
    palm_pose_in_chest,
    prev_action_targets,
)

__all__ = [
    "action_delay",
    "body_angular_velocity", "body_contact_flags", "body_linear_velocity", "body_pose_in_chest", "palm_distance_error", "palm_pose_in_chest",
    "closest_fingertip_dist", "closest_keypoint_max_dist", "curriculum_state", "curriculum_success",
    "dr_params", "episode_step", "fingertip_contact_steps", "fingertip_penetration_depth",
    "fingertip_relative_pos", "fingertip_relative_pose", "fingertip_relative_vel",
    "curriculum_hold_progress", "gate_success", "goal_dist_error", "goal_keypoints", "grip_count",
    "hand_contact_force", "hand_object_force_magnitude", "instantaneous_reward",
    "joint_accelerations", "joint_gravcomp_torque_obs", "joint_pd_torque_obs",
    "joint_pose_error", "joint_positions", "joint_state", "joint_torque_obs",
    "joint_velocities", "last_action", "object_angular_velocity",
    "object_goal_keypoint_success", "object_lifed",
    "object_keypoints", "object_linear_velocity", "object_pose", "object_state_world",
    "object_variant",
    "prev_action_targets",
]
